version : '3'

services:
  db: 
    image: postgres:latest
    container_name: data_base
    restart: always
    tty: true
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library_db